-- TABLA ENCARGADA DE ALMACENAR LOS TIPOS DE ESTADOS DE UNA PERSONA CASADO SOLTERO ETC
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'TIPOSESTADO') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
   DROP TABLE TIPOSESTADO
GO 

CREATE TABLE TIPOSESTADO(
	CODIGO		INT IDENTITY(1,1)	NOT NULL, --
	NOMBRE		VARCHAR(200)		NOT NULL  -- NOMBRE DEL ESTADO EJEMPLO CASADO SOLTERO ETC
)
GO

ALTER TABLE TIPOSESTADO ADD CONSTRAINT SYSTEMP01TIPOSESTADO PRIMARY KEY (CODIGO)  
GO

INSERT INTO TIPOSESTADO(NOMBRE) VALUES('SOLTERO(A)') 
GO
INSERT INTO TIPOSESTADO(NOMBRE) VALUES('CASADO(A)') 
GO
INSERT INTO TIPOSESTADO(NOMBRE) VALUES('UNION LIBRE(A)') 
GO

SELECT CODIGO, NOMBRE FROM TIPOSESTADO