-- TABLA TEMPORAL PARA ACTUALIZAR DATOS CON LOS DATOS QUE SE CAPTURAN EN LA PAGINA
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'USUARIOS') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
   DROP TABLE USUARIOS
GO 

CREATE TABLE USUARIOS(
	CODIGO					INT IDENTITY(1,1)	NOT NULL, --
	NOMBRES					VARCHAR(200)		NOT NULL, -- NOMBRES
	APELLIDO			    VARCHAR(40)			NOT NULL, -- APELLIDOS
	FECHA_NACIMIENTO		DATETIME			NOT NULL, -- FECHA DE NACIMIENTO
	FOTO_USUARIO			VARCHAR(MAX)  		NULL, -- FOTO DEL USUARIO
	ESTADO_CIVIL			INT					NOT NULL, -- ESTADO CIVIL
	TIENE_HERMANOS			BIT					NOT NULL, -- TIENE HERMANOS
)
GO

-- SE CREA LLAVE PRIMARIA PARA EL IDENTIFICADOR DE LA TABLA
ALTER TABLE USUARIOS ADD CONSTRAINT SYSTEMP01USUARIOS PRIMARY KEY (CODIGO)  
GO
-- SE CREA LLAVE FORANEA PARA OBTENER EL ESTADO CIVIL DE UNA PERSONA SOLTERO CASADO ETC
ALTER TABLE USUARIOS  WITH CHECK ADD FOREIGN KEY(CODIGO) REFERENCES TIPOSESTADO (CODIGO)
GO

-- DBCC CHECKIDENT (USUARIOS, RESEED, 0)
-- DELETE FROM USUARIOS		

SELECT U.CODIGO, U.NOMBRES, U.APELLIDO, U.FECHA_NACIMIENTO,
       U.FOTO_USUARIO, T.NOMBRE AS ESTADO_CIVIL, U.TIENE_HERMANOS
FROM USUARIOS U
INNER JOIN TIPOSESTADO T ON T.CODIGO =U.CODIGO